import Head from "next/head";
import { BsFillMoonStarsFill, BsPlayCircle } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillMessage } from "react-icons/ai";
import Image from "next/image";
import quran from "../public/quran.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/pen.png";
import web1 from "../public/youth.png";
import web2 from "../public/savings.png";
import web3 from "../public/storic.png";
import web4 from "../public/socio.png";
import * as React from "react";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Modal from "@mui/material/Modal";
import picture from "../public/picture1.png";
import { useState } from "react";
import ContactUs from "./components/ContactUs";
// import Resume from "../public/Resume.pdf";

const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 400,
  bgcolor: "background.paper",
  border: "1px solid teal",
  boxShadow: 24,
  p: 4,
};

const ServiceCard = ({ image, service, description }) => {
  return (
    <div className=" text-center shadow-lg p-10 rounded-xl my-10 bg-gray-200 dark:bg-gray-700">
      <Image src={image} width={100} height={100} />
      <h3 className="text-lg font-medium pt-8 pb-2 dark:text-teal-50 sm:text-lg">
        {service}
      </h3>
      <p className=" py-2 dark:text-yellow-50 sm:text-sm">{description}</p>
    </div>
  );
};

const DefaultCard = ({ image, title, tech, github, live }) => {
  return (
    <div className="p-10 bg-gradient-to-b from-teal-700 w-full basis-1/3 flex-1 ">
      <h3 className="text-white font-bold mb-4">2. Card with image</h3>
      <div className="bg-white rounded-lg shadow-lg bg-auto hover:bg-contain">
        <Image src={image} alt="" className="rounded-t-lg" />
        <div className="p-6 dark:bg-gray-700">
          <h2 className="font-bold mb-2 text-2xl text-teal-700 dark:text-white sm:text-base ">
            {title}
          </h2>
          <p className="text-teal-700 mb-2 dark:text-teal-200 sm:text-sm">
            {tech}
          </p>

          <div className="relative text-2xl lg:gap-16 md:gap-12 sm:gap-4 py-3 text-gray-700">
            <a
              href={github}
              className="text-teal-600 hover:text-teal-300 underline lg:text-2xl md:text-1xl sm:text-sm"
            >
              <AiFillGithub className="absolute bottom-0 right-0 dark:text-white" />
            </a>
            <a
              href={live}
              className="text-teal-600 hover:text-teal-300 underline lg:text-2xl md:text-xl sm:text-sm"
            >
              <BsPlayCircle className="absolute bottom-0 right-10 dark:text-white" />
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};
export default function Home() {
  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  const [darkMode, setdarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sarfaraz Ahmed Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-teal-50 px-10 md:px-20 lg:px-40 dark:bg-gradient-to-r from-gray-700 to-gray-900">
        <section className="min-h-screen">
          <nav className=" py-10  mb-10 flex  justify-between">
            <h1 className=" text-xl font-burtons dark:text-white sm:text-sm md:text-2xl">
              Portfolio
            </h1>
            <ul className="flex  items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setdarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-white sm:text-lg md:text-2xl"
                />
              </li>
              <li>
                <a
                  href="https://drive.google.com/file/d/1L0q9-iUnU1an3pp7--yaMAlN74qrAaKE/view"
                  download
                  className=" bg-gradient-to-r from-cyan-500 to-teal-600 text-white px-4 py-2 rounded-md ml-8 sm:text-sm md:text-lg"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-200 sm:text-4xl">
              Sarfaraz Ahmed
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white sm:text-xl">
              Front End Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl  mx-auto dark:text-yellow-50 sm:text-sm">
              I’m a Computer Science Student specializing in building
              exceptional digital experiences. Currently, I’m focused on
              building accessible, human-centered products at Upstatement using
              React JS and other latest technologies.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 sm:text-2xl sm:gap-6">
            <a href="https://github.com/SarfarazAhmed1012">
              <AiFillGithub className="dark:text-white sm:text-lg md:text-2xl lg:text-4xl" />
            </a>
            <a href="https://www.linkedin.com/in/sarfaraz-ahmed-215ba016a/">
              <AiFillLinkedin className="dark:text-white sm:text-lg md:text-2xl lg:text-4xl" />
            </a>
            <a href="https://mail.google.com/mail/?view=cm&fs=1&to=sarfarazahmed1012@gmail.com">
              <AiFillMessage className="dark:text-white sm:text-lg md:text-2xl lg:text-4xl" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-700 rounded-full w-80 h-80 mt-20 overflow-hidden sm:w-40 sm:h-40 md:w-96 md:h-96">
            <Image className="" src={picture} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="lg:text-4xl md:text-4xl py-1 dark:text-white sm:text-xl ">
              Services I offer
            </h3>
            <p className=" pt-2 leading-8 text-gray-800 dark:text-yellow-50 sm:text-sm lg:text-lg md:text-lg">
              Freelance Web Designer & Developer based in Karachi, Pakistan.
              Experienced in designing & developing functional websites.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <ServiceCard
              image={design}
              service="Responsive Website Design"
              description="Having a responsive layout means that your website fluidly resizes for optimal viewing regardless of the screen size or device (e.g. iPhone, iPad)."
            />
            <ServiceCard
              image={consulting}
              service="Content Writing"
              description="Professional website content writing by our in-house copywriter. We also offer copy-writing for optimising your website's SEO."
            />
            <ServiceCard
              image={code}
              service="Website Development"
              description="I like to code things from scratch, create all types of web-based application, ensure great experience for users and enjoy bringing ideas to life in the browser."
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="lg:text-4xl md:text-4xl py-1 dark:text-white sm:text-xl">
              Portfolio
            </h3>
            <p className=" pt-2 leading-8 text-gray-800 dark:text-yellow-50 sm:text-sm lg:text-lg md:text-lg">
              I don’t like to define myself by the work I’ve done. I define
              myself by the work I want to do. Skills can be taught, personality
              is inherent. I prefer to keep learning, continue challenging
              myself, and do interesting things that matter.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <DefaultCard
              image={quran}
              title="QuranRecite"
              tech="React JS, CSS, API"
              github="https://github.com/SarfarazAhmed1012/Quran-Recitation-Application"
              live="https://quranrecitation.netlify.app/"
            />
            <DefaultCard
              image={web1}
              title="YouthTube"
              tech="React JS, Material UI V5, Rapid API"
              github="https://github.com/SarfarazAhmed1012/youtube-clone"
              live="https://youthtube.netlify.app/"
            />
            <DefaultCard
              image={web2}
              title="Expense Tracker"
              tech="MERN, Redux Toolkit, Chart JS, Tailwind CSS"
              github="https://github.com/SarfarazAhmed1012/expense_tracker_MERN_semester_project"
              live=""
            />
            <DefaultCard
              image={web4}
              title="Sociofy (Social Media UI)"
              tech="React JS, Material UI"
              github="https://github.com/SarfarazAhmed1012/social-media-ui-material-ui"
              live="https://sociofyy.netlify.app/"
            />
            <DefaultCard
              image={web3}
              title="Admin Dashboard"
              tech="React JS, Context API, Syncfusion"
              github="https://github.com/SarfarazAhmed1012/Admin-Dashboard-using-React-JS"
              live="https://syncfusion-admin-dashboard-1012.netlify.app/"
            />
          </div>
        </section>
        <section>
          <div className=" text-center p-10 text-2xl">
            <Button
              onClick={handleOpen}
              variant="outlined"
              className=" font-burtons sm:text-sm md:text-lg bg-gradient-to-r from-cyan-500 to-teal-600 text-white px-4 py-2 rounded-md lg:ml-8 md:ml-8 sm:ml-2
              "
            >
              Contact me
            </Button>
          </div>
          <div>
            <Modal
              open={open}
              onClose={handleClose}
              aria-labelledby="modal-modal-title"
              aria-describedby="modal-modal-description"
              className="bg-gradient-to-b from-teal-700 sm:text-sm"
            >
              <Box
                sx={style}
                className="sm:text-sm bg-gradient-to-r from-teal-700 to-teal-900 dark:from-gray-700"
                maxWidth="sm"
              >
                <ContactUs />
              </Box>
            </Modal>
          </div>
          {/* <div className="grid place-content-center ">
            <ContactUs />
          </div> */}
        </section>
      </main>
    </div>
  );
}

{
  /* <div className="basis-1/3 flex-1">
<Image
  className="rounded-lg object-cover"
  width={"100%"}
  height={"100%"}
  layout="responsive"
  src={web2}
/>
</div>
<div className="basis-1/3 flex-1">
<Image
  className="rounded-lg object-cover"
  width={"100%"}
  height={"100%"}
  layout="responsive"
  src={web3}
/>
</div>
<div className="basis-1/3 flex-1">
<Image
  className="rounded-lg object-cover"
  width={"100%"}
  height={"100%"}
  layout="responsive"
  src={web4}
/>
</div>
<div className="basis-1/3 flex-1">
<Image
  className="rounded-lg object-cover"
  width={"100%"}
  height={"100%"}
  layout="responsive"
  src={web5}
/>
</div>
<div className="basis-1/3 flex-1">
<Image
  className="rounded-lg object-cover"
  width={"100%"}
  height={"100%"}
  layout="responsive"
  src={web6}
/>
</div> */
}
